Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -53,9 +53,37 @@ jobs:
           -H "X-GitHub-Api-Version: 2022-11-28" 
           "https://api.github.com/repos/KhalimulinDD/test_project_ui_magento_pw/actions/artifacts/$REPORT_ID/zip" -o pages.zip
           
-      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
-      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
-      - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results 
+      - name: Download and unzip artifacts
+        run: |
+          # Проверка существования artifacts.zip
+          if [[ -f "artifacts.zip" ]]; then
+              mkdir -p allure-results && unzip artifacts.zip -d allure-results || true
+          else
+              echo "artifacts.zip not found. Skipping this step."
+          fi
+      - name: Unzip pages.zip if it exists
+        run: |
+          if [[ -f "pages.zip" ]]; then
+              mkdir -p old_pages pages_history && unzip pages.zip -d old_pages || true
+              if [[ -f "old_pages/artifact.tar" ]]; then
+                  tar -xvf old_pages/artifact.tar -C pages_history || true
+              else
+                  echo "artifact.tar not found in old_pages. Skipping tar extraction."
+              fi
+          else
+              echo "pages.zip not found. Skipping this step."
+          fi
+
+      - name: Copy history if it exists
+        run: |
+          if [[ -d "pages_history/history" ]]; then
+              mkdir -p allure-results
+              cp -r pages_history/history/* allure-results || true
+              cp -r pages_history/history allure-results || true
+          else
+              echo "pages_history/history directory not found. Skipping copy step."
+          fi
+          
       - name: Store allure history
         uses: actions/upload-artifact@v4
         with:
